<?xml version="1.0"?>
<package format="3">

  <name>carrier_description</name>

  <version>0.0.1</version>

  <description>
    UR5 carrier manipulator with custom bin manipulator.
  </description>

  <maintainer email="shanmukha@example.com">
    shanmukha
  </maintainer>

  <license>Apache-2.0</license>

  <exec_depend>xacro</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <depend>ur_description</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>

</package>
